### ISSUE TITLE
помогите пожалуйста help me pleas  

### ISSUE THREAD

**Issue by danya0811** [arsuhinars/game_console#1]
У меня есть код для игры но я не знаю как его вставить в приставку в описании написана как я не понимаю помогите пожалуйста

**Comment by arsuhinars** [comment]
Тебе необходимо прошить микроконтроллер через Arduino IDE. Если у тебя что-то наподобие Arduino Uno или Nano, то посмотри лучше ролик, где объясняется вся работа с ардуинками https://www.youtube.com/watch?v=G7bZJhWD01c. Если у тебя голый микроконтроллер, то прочитай про их прошивку тут https://alexgyver.ru/lessons/programmer-tips/
